### ISSUE TITLE
About pre-trained models downloading

### ISSUE THREAD

**Issue by songnnnn** [sustainlab-group/geography-aware-ssl#1]
Hi there
I found **http 404** error clicking on your link when downloading the pre-trained ResNet-50 models, could you please check what's going on with the link?
Much appreciation, this means a lot to me.

**Comment by zcalhoun** [comment]
I too am having this same issue -- is it possible to get this model?

**Comment by uzkent** [comment]
@songnnnn @zcalhoun You can find the checkpoints in the readme. Can you please try it again?
